#!/usr/bin/env zsh

SENSOR_CALIBRATION="/home/berlukas/Documents/workspace/maplab_experimental/src/maplab_experimental/maplab/maplab-launch/config/lidarmace/calib/lidarmace-sensors.yaml"
REST=$@

rosrun lidar_image_projection lidar_image_projection \
  --v=7 \
  --alsologtostderr \
  --sensor_calibration_file=$SENSOR_CALIBRATION \
  --selected_camera_id="61f5c269e1f9608678291fa5fdd81941" \
  --selected_lidar_id="abf123479caf7592b35518478a2fe08d" \
  --vio_camera_topic_suffix="" \
  --correction_alpha=0.00 \
  --correction_beta=-0.000 \
  --correction_gamma=0.00 \
  --correction_x=0.00 \
  --correction_y=0.0 \
  --correction_z=0.0 \
  $REST
