#!/usr/bin/env zsh

SENSOR_CALIBRATION="/home/berlukas/Documents/workspace/maplab/src/maplab_private/applications/maplab_node/share/example_calibrations/armadillo.yaml"
REST=$@

rosrun maplab_camera_info_publisher maplab_camera_info_publisher \
  --v=3 \
  --alsologtostderr \
  --sensor_calibration_file=$SENSOR_CALIBRATION \
  --image_scale_factor=1.0 \
  --start_service=true \
	--vio_camera_topic_suffix="" \
  $REST
