#!/usr/bin/env zsh

SENSOR_CALIBRATION="/home/berlukas/Documents/workspace/darpa_2/src/darpa_subt_mapping/darpa_subt_calib/share/anymal-rsl-cerberus-compressed.yaml"
REST=$@

rosrun maplab_camera_info_publisher maplab_camera_info_publisher \
  --v=3 \
  --alsologtostderr \
  --sensor_calibration_file=$SENSOR_CALIBRATION \
  --image_scale_factor=1.0 \
  --start_service=true \
	--vio_camera_topic_suffix="" \
  --processed_topic_suffix="" \
	--image_rotation_angle_deg=0 \
	--republish_grayscale=false \
	--image_apply_clahe_histogram_equalization=false \
  --compressed_image_encoding="mono8" \
  $REST
