#!/usr/bin/env zsh

REST=$@

rosrun ply_publisher ply_publisher \
  --v=3 \
  --alsologtostderr \
  --publish_topic="/point_cloud" \
  --PLY_directory="/home/berlukas/Documents/ply_datasets/phaser_test/" \
  $REST
