#!/usr/bin/env zsh

REST=$@

rosrun ply_publisher ply_publisher \
  --v=3 \
  --alsologtostderr \
  --publish_topic="/ply_point_cloud" \
  --PLY_directory="/media/berlukas/Data/data/cdpgo/teaser_img/init/" \
  --frame_id="map" \
  --enable_suffix \
  $REST
