#!/usr/bin/env zsh
REST=$@

rosrun image_debayer image_debayer \
   --alsologtostderr=1 \
   --v=3 \
   --cam_topic="/alphasense_driver_ros/cam1" \
   --color_topic="/alphasense_driver_ros/cam1/processed" \
   --simple_wb_saturation_percentage=10.0 \
   --image_rotation_angle_deg=180 \
   --export_image_path="" \
   --bayer_pattern="GR2BGR" \
   $REST
